[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run build -- --configuration production",
  "cp ./nginx.conf /etc/nginx/nginx.conf"
]

[start]
cmd = "nginx -g 'daemon off;'"

[variables]
PORT = "80"
