[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npx serve dist/electro-ecom -s -l $PORT"

[variables]
NODE_ENV = "production"
